edit_de_project:
  target: staging
  outputs:
    raw:
      type: bigquery
      method: oauth
      project: data-eng-dev-437916
      dataset: data_eng_project_group3
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      priority: interactive
      threads: 4 # Must be a value of 1 or greater 
    staging:
      type: bigquery
      method: oauth
      project: data-eng-dev-437916
      dataset: data_eng_project_group3
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      priority: interactive
      threads: 4 # Must be a value of 1 or greater 
    marts:
      type: bigquery
      method: oauth
      project: data-eng-dev-437916
      dataset: data_eng_project_group3
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      priority: interactive
      threads: 4 # Must be a value of 1 or greater
