version: 2

sources:
  - name: raw_dataset
    database:  data-eng-dev-437916
    schema: data_eng_project_group3_raw  
    tables:
      - name: routes
      - name: lines
      - name: stops
      - name: municipalities
      - name: dates
      - name: historical_stop_times
      - name: periods
      - name: shapes
      - name: stop_times
      - name: trips
      - name: weather_last_fivedays
